server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gussoft/configurations-service
          search-paths: data-config
          default-label: master
  application:
    name: config-service
